### ISSUE TITLE
IRC ...

### ISSUE THREAD

**Issue by SvenDowideit** [machine-drivers/discussion#10]
I've created #machine-drivers on freenode - I'd rather not create another slack/gitter, but others might prefer other things :)

@ALL

**Comment by gbraad** [comment]
@machine-drivers/hyperkit @machine-drivers/kvm @machine-drivers/qemu @machine-drivers/vmware @machine-drivers/xhyve Please, let's discuss on IRC

**Comment by gbraad** [comment]
Created a Riot alias: https://riot.im/app/#/room/#machine-drivers:matrix.org
