### ISSUE TITLE
import and merge vmware drivers?

### ISSUE THREAD

**Issue by SvenDowideit** [machine-drivers/discussion#5]
https://github.com/kubernetes/minikube/pull/2118

cos its really weird to have so many

**Comment by gbraad** [comment]
@anfernee WDYT?

**Comment by anfernee** [comment]
@SvenDowideit and @gbraad our team is still in discussion where to host the drivers. should all drivers be in this organization or under the individual company's org. Is this organization a foundation or something?

**Comment by nerro** [comment]
look forward to get working minikube with vmware workstation :wink:

**Comment by gbraad** [comment]
we are not a foundation, but rather a community representation. we are doing this with the ideal of keeping maintenance available to all drivers as they are part of this organization, as too often (even for company repos) we have seen deprecation or low maintenance/stganation while the community was/is more than willing to take over.

**Comment by SvenDowideit** [comment]
but - if joining a foundation, or something like that helps, we'd be open to talking about it :)

**Comment by anfernee** [comment]
anyway, let's put the working code and testing infrastructure together first. I personally don't really mind where it lives as long as it is working ;)

**Comment by frapposelli** [comment]
I believe we should start this process by moving @anfernee code into its own repo under `machine-drivers`, WDYT? @gbraad @SvenDowideit

**Comment by gbraad** [comment]
I do not want to introduce a fork, but rather see the driver author doing
so himself.

**Comment by frapposelli** [comment]
@gbraad sorry, that's what I meant, @anfernee and I work @vmware in the same group.

**Comment by gbraad** [comment]
In that case... Yes, please... Go ahead!

**Comment by anfernee** [comment]
sorry for the delay. occupied with events internally. The vmware repo is online. It basically works. And we need to work on docs, contributing guide, testing on different platforms, etc. We'll track those inside that repo.

**Comment by gbraad** [comment]
I think we can close this issue and create new issues accordingly in the driver or this discussion repo.
