### ISSUE TITLE
import docker-machine-xhyve driver

### ISSUE THREAD

**Issue by zchee** [machine-drivers/discussion#7]
Hi, all.
At first, Sorry for late response.

I agreed move `docker-machine-driver-xhyve` to this organization.
What should I do first? Transfer to this org is OK? or just copy all source?

**Comment by praveenkumar** [comment]
@zchee Best to transfer it to this org, this way all the issue and PR will be in place. Thanks for creating the issue, I was planning to create it for some time now :)

**Comment by gbraad** [comment]
Transfer would be the best approach. After this you can create a fork in your own namespace and add a redirect notice if needed at the top of the project.

**Comment by zchee** [comment]
@praveenkumar @gbraad 
I see. I'll transfer to `machine-drivers` org after some checking point(my accounts permission on org, prepare fix `docker-machine-driver-xhyve` import path or etc)

**Comment by zchee** [comment]
@praveenkumar @gbraad cc: @dlorenc I'll transfer https://github.com/zchee/docker-machine-driver-xhyve to https://github.com/machine-drivers org today.
Also, try to fix import path and change to directory architecture if have time.

Anyway, the transfer repository is the first approach. will do.

**Comment by zchee** [comment]
done 🎉 
https://github.com/machine-drivers/docker-machine-driver-xhyve

**Comment by gbraad** [comment]
Thanks... awesome to this! I see it automatically forwards to the organization... nice.
Hopefully next week we have some more time to assist with some of the issues, open questions, etc.

**Comment by zchee** [comment]
Yeah, GitHub will cache transferred url, but it has expired. I'll fix package import path until expired.
