### ISSUE TITLE
Consider create GitHub Team

### ISSUE THREAD

**Issue by zchee** [machine-drivers/discussion#8]
I consider creating GitHub Team in https://github.com/machine-drivers. like:
- @machine-drivers
  - @machine-drivers/xhyve
  - @machine-drivers/hyperkit
  - @machine-drivers/qemu
  - etc...

Because the `machine-drivers` organization project has started. Also, many developers already joined this org.
Create team would you be helpful to catch notifications or etc.

What do you think about it?

**Comment by zchee** [comment]
/cc @aaron-prindle @afbjorklund @anfernee @dhiltgen @dlorenc @dougm @frapposelli @gbraad @LalatenduMohanty @praveenkumar @r2d4 @SvenDowideit @zakame 
(a lot of cc... that's why to write this proposal lol)

**Comment by zakame** [comment]
Yes please!  That way we can also distribute the maintenance load across
the teams :+1:

**Comment by frapposelli** [comment]
👍

**Comment by SvenDowideit** [comment]
ok, so what's the best way to allow each team to manage its own users?
I kinda fall into the "lets make everyone admin" group - so perhaps someone wants to add some sanity-rule :)

I've created one group per existing repo - @machine-drivers/qemu @machine-drivers/hyperkit @machine-drivers/xhyve @machine-drivers/vmware and have added the most obvioud contributors to them

I'm not sure how best to manage an `all` members group though.

**Comment by afbjorklund** [comment]
I have no idea* what a "team" or a "project" is, but if you think it is useful then go for it...
(that group "mention" feature is probably useful all by itself - or maybe it "could be")

\* _ok, I did find:_
* https://help.github.com/articles/organizing-members-into-teams/
